### ISSUE TITLE
Examples Data

### ISSUE THREAD

**Issue by chkone** [dlaptev/RobustPCA#2]
Hello,

Did you know where can I found the data you used for example/inpainting.m?
moon.tif & text.png

Thanks

**Comment by dlaptev** [comment]
Hi @chkone, thanks for your interest.

Both "moon.tif" and "text.png" are [Matlab's builtin demo images](https://ch.mathworks.com/matlabcentral/answers/54439-list-of-builtin-demo-images#answer_66143). So there is no need to download them from anywhere, they should be directly available.

If you are using something other than Matlab, you can just look for the images online like "[text.png Matlab](https://www.google.com/search?q=text.png+Matlab&tbm=isch)".
