### ISSUE TITLE
algorithm stopping condition

### ISSUE THREAD

**Issue by iverson333** [dlaptev/RobustPCA#4]
Thanks for your code. I find your implementation adds the number of iterations as an additional constraint for stopping criteria apart from the tolerance of residuals of original matrix and decomposed low-rank and sparse component, which is useful in practice. I wonder if you ever experienced that the magnitude of residual keeps increasing (which means the algo will never converge in the original paper's setting), and why this happen?

**Comment by dlaptev** [comment]
Good question, @iverson333 ! The "maximum number of iterations" parameter there is mostly for convenience: to prevent you waiting for convergence longer than you want to. If my understanding is correct, the PCP problem is convex and therefore the method should _theoretically_ always converge given enough time.

However in practice there could be some numerical problems. If the matrix is very large and the values are very small, then some intermediate steps (mainly SVD) can be inexact. This could potentially lead to some oscillating behaviour. That said, I never stumbled upon such an example in real world scenarios myself.

**Comment by dlaptev** [comment]
Please feel free to reopen/comment if you have related questions or if you found a particular example you would like to share.

**Comment by iverson333** [comment]
Cool, thanks!
